app:
    resource: "@AppBundle/Controller/"
    type:     annotation

main:
    path:      /
    defaults:  { _controller: AppBundle:Main:index }

admin_main:
    path:      /admin
    defaults:  { _controller: AppBundle:Admin:index }

admin_add_item:
    path: /admin/new-product
    defaults: { _controller: AppBundle:Admin:addItem }
