# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.logger:
        class: AppBundle\Helper\AppLogger
        arguments: ["@logger", "@security.token_storage"]

    app.flash.message:
        class: AppBundle\Helper\FlashMessage
        arguments: ["@session"]

    app.mailer:
        class: AppBundle\Helper\AppMailer
        arguments: ["@mailer", "@templating", "@security.token_storage"]
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
